#!/usr/bin/env python3
"""Stage physical robot packages without editing the original workspace."""
import argparse
from pathlib import Path
import shutil
import xml.etree.ElementTree as ET

PACKAGES = {
    "limo_msgs": "limo_ros2/limo_msgs",
    "limo_base": "limo_ros2/limo_base",
    "limo_bringup": "limo_ros2/limo_bringup",
    "limo_description": "limo_ros2/limo_description",
    "custom_start": "custom_start",
    "ydlidar_ros2_driver": "ydlidar_ros2_driver",
    "astra_camera_msgs": "ros2_astra_camera/astra_camera_msgs",
    "astra_camera": "ros2_astra_camera/astra_camera",
}
CAMERA_PACKAGES = {"astra_camera", "astra_camera_msgs"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--without-camera", action="store_true")
    parser.add_argument("--manifests-only", action="store_true")
    args = parser.parse_args()
    source = args.source.resolve()
    destination = args.destination.resolve()
    if source == destination or source in destination.parents or destination in source.parents:
        parser.error("Source and destination must be separate directories")
    selected = {name: source / relative for name, relative in PACKAGES.items()
                if not args.without_camera or name not in CAMERA_PACKAGES}
    for name, directory in selected.items():
        manifest = directory / "package.xml"
        if not manifest.is_file() or ET.parse(str(manifest)).getroot().findtext("name") != name:
            parser.error("Missing or invalid source manifest: {}".format(manifest))

    marker = destination / ".limo-generated"
    if destination.exists() and any(destination.iterdir()) and not marker.is_file():
        parser.error("Refusing to overwrite a directory not generated by this profile")
    destination.mkdir(parents=True, exist_ok=True)
    marker.touch()
    # Only remove this helper's previous generated package copies.
    for name in PACKAGES:
        old = destination / name
        if old.exists():
            shutil.rmtree(str(old))
    for name, directory in selected.items():
        target = destination / name
        if args.manifests_only:
            target.mkdir()
        else:
            shutil.copytree(str(directory), str(target), ignore=shutil.ignore_patterns(
                ".git", "__pycache__", "*.pyc", "build", "install", "log", "COLCON_IGNORE"))
        tree = ET.parse(str(directory / "package.xml"))
        package = tree.getroot()
        for entry in list(package):
            if not entry.tag.endswith("depend"):
                continue
            dependency = (entry.text or "").strip()
            if dependency == "limo_car" or dependency.startswith("gazebo") or (
                    args.without_camera and dependency in CAMERA_PACKAGES):
                package.remove(entry)
        tree.write(str(target / "package.xml"), encoding="utf-8", xml_declaration=True)
        if name == "custom_start" and not args.manifests_only:
            # The source package combines robot and simulator launch resources.
            (target / "launch/limo_circuit.launch.py").unlink(missing_ok=True)
            for resource in ("models", "worlds"):
                if (target / resource).is_dir():
                    shutil.rmtree(str(target / resource))
        print("Prepared {}".format(name))


if __name__ == "__main__":
    main()
